# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strings', '0005_auto_20160602_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='StringStringSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strings.String')),
                ('string_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strings.StringSet')),
            ],
        ),
    ]
