# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings', '0006_stringstringset'),
    ]

    operations = [
        migrations.AddField(
            model_name='stringstringset',
            name='note',
            field=models.CharField(default='C1', max_length=3),
        ),
    ]
