# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings', '0009_auto_20160602_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='StringSetConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='stringstringset',
            name='note',
        ),
    ]
