# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings', '0010_auto_20160602_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('scale_length_imperial', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='StringSetConfiguration',
        ),
        migrations.RenameField(
            model_name='stringstringset',
            old_name='string_set',
            new_name='stringset',
        ),
        migrations.RemoveField(
            model_name='stringset',
            name='strings',
        ),
        migrations.AddField(
            model_name='stringstringset',
            name='note',
            field=models.CharField(default='A', max_length=3),
            preserve_default=False,
        ),
    ]
