# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings', '0012_auto_20160610_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='string',
            name='unit_weight_imperial',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
