# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings', '0015_string_surface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='string',
            name='surface',
        ),
        migrations.AddField(
            model_name='string',
            name='material',
            field=models.CharField(choices=[('st', 'Steel'), ('nl', 'Nylon')], default='st', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='string',
            name='winding',
            field=models.CharField(choices=[('p', 'Plain'), ('w', 'Wound'), ('wp', 'Wound filed down')], default='w', max_length=128),
            preserve_default=False,
        ),
    ]
