# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strings', '0016_auto_20160610_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='stringset',
            name='base_stringset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='strings.StringSet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stringset',
            name='scale_lengths',
            field=models.ManyToManyField(to='strings.ScaleLength', verbose_name='Recommended scale lengths'),
        ),
    ]
