# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strings', '0017_auto_20160610_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringset',
            name='base_stringset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='strings.StringSet'),
        ),
    ]
