# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strings', '0018_auto_20160610_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='string',
            name='unit_weight_imperial',
        ),
    ]
