# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('strings', '0019_remove_string_unit_weight_imperial'),
    ]

    operations = [
        migrations.AddField(
            model_name='string',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.Brand'),
        ),
    ]
